### ISSUE TITLE
Use of deprecated routeConfig in fastify

### ISSUE THREAD

**Issue by gugu** [SkeLLLa/fastify-metrics#86]
```
(node:463) [FSTDEP016] FastifyDeprecation: You are accessing the deprecated "request.routeConfig" property. Use "request.routeOptions.config" instead. Property "req.routeConfig" will be removed in `fastify@5`.
FastifyDeprecation: You are accessing the deprecated "request.routeConfig" property. Use "request.routeOptions.config" instead. Property "req.routeConfig" will be removed in `fastify@5`.
    at Object.emit (/srv/shorturl_redirector/node_modules/process-warning/index.js:55:13)
    at _Request.get (/srv/shorturl_redirector/node_modules/fastify/lib/request.js:217:15)
    at FastifyMetrics.defaultGetRouteLabel (/srv/shorturl_redirector/node_modules/fastify-metrics/src/fastify-metrics.ts:88:15)
    at Object.<anonymous> (/srv/shorturl_redirector/node_modules/fastify-metrics/src/fastify-metrics.ts:337:28)
    at onResponseHookIterator (/srv/shorturl_redirector/node_modules/fastify/lib/hooks.js:270:10)
    at next (/srv/shorturl_redirector/node_modules/fastify/lib/hooks.js:243:18)
    at hookRunner (/srv/shorturl_redirector/node_modules/fastify/lib/hooks.js:265:5)
    at Response.onResFinished (/srv/shorturl_redirector/node_modules/fastify/lib/reply.js:775:7)
    at Response.emit (node:events:523:35)
    at Response.emit (node:domain:489:12)
```

**Comment by philb90** [comment]
The warning appears as of Fastify v4.23.0

**Comment by SkeLLLa** [comment]
Likely closed by #88. Please check.

**Comment by nivr4** [comment]
Hey, i updated the fastify-metrics to 10.3.1 and still get this warnings

`(node:36688) [FSTDEP016] FastifyDeprecation: You are accessing the deprecated "request.routeConfig" property. Use "request.routeOptions.config" instead. Property "req.routeConfig" will be removed in `fastify@5`.
    at Object.emit (/node_modules/process-warning/index.js:55:13)
    at Request.get (/node_modules/fastify/lib/request.js:217:15)
    at Object.<anonymous> (/node_modules/fastify-metrics/src/fastify-metrics.ts:296:21)
    at hookIterator (/node_modules/fastify/lib/hooks.js:409:10)
    at next (/node_modules/fastify/lib/hooks.js:243:18)
    at hookRunner (/node_modules/fastify/lib/hooks.js:265:5)
    at Object.routeHandler [as handler] (/node_modules/fastify/lib/route.js:482:7)
    at Router.callHandler (/node_modules/find-my-way/index.js:398:14)
    at Router.lookup (/node_modules/find-my-way/index.js:376:17)
    at Server.preRouting (/node_modules/fastify/fastify.js:844:14)
(node:36688) [FSTDEP017] FastifyDeprecation: You are accessing the deprecated "request.routerPath" property. Use "request.routeOptions.url" instead. Property "req.routerPath" will be removed in `fastify@5`.
    at Object.emit (/node_modules/process-warning/index.js:55:13)
    at Request.get (/node_modules/fastify/lib/request.js:175:15)
    at Object.<anonymous> (/node_modules/fastify-metrics/src/fastify-metrics.ts:317:28)
    at hookIterator (/node_modules/fastify/lib/hooks.js:409:10)
    at next (/node_modules/fastify/lib/hooks.js:243:18)
    at hookRunner (/node_modules/fastify/lib/hooks.js:265:5)
    at Object.routeHandler [as handler] (/Users/nivraviv/Desktop/SRE/ip-geolocation-resolver/node_modules/fastify/lib/route.js:482:7)
    at Router.callHandler (/node_modules/find-my-way/index.js:398:14)
    at Router.lookup (/node_modules/find-my-way/index.js:376:17)
    at Server.preRouting (/node_modules/fastify/fastify.js:844:14)`

**Comment by SkeLLLa** [comment]
@rozzilla merged.

**Comment by rozzilla** [comment]
Tested right now last version, no more deprecation warning 👌🏼 
I think we can consider this issue as closed @SkeLLLa 👍🏼 
Thanks for merging it! 🙏🏼
